-- MySQL Script generated by MySQL Workbench
-- Mon 05 Nov 2018 02:47:40 PM PST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dtc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dtc` ;

-- -----------------------------------------------------
-- Schema dtc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dtc` ;
USE `dtc` ;

-- -----------------------------------------------------
-- Table `dtc`.`debate_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dtc`.`debate_session` (
  `id` INT NOT NULL,
  `matchid` CHAR(36) NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `topic` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `pk_matchid` USING BTREE (`matchid`) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dtc`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dtc`.`users` (
  `id` INT NOT NULL,
  `xp` INT NULL,
  `username` VARCHAR(45) NULL,
  `credits` INT NULL,
  `badges` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dtc`.`debate_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dtc`.`debate_review` (
  `id` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `review` TEXT NOT NULL,
  `aggrement` TINYINT NOT NULL,
  `users_id` INT NOT NULL,
  `debate_session_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_debate_review_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_debate_review_debate_session1_idx` (`debate_session_id` ASC) VISIBLE,
  CONSTRAINT `fk_debate_review_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `dtc`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_debate_review_debate_session1`
    FOREIGN KEY (`debate_session_id`)
    REFERENCES `dtc`.`debate_session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dtc`.`debate_session_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dtc`.`debate_session_users` (
  `users_id` INT NOT NULL,
  `debate_session_id` INT NOT NULL,
  `badges` TEXT NULL,
  `wasFor` TINYINT NULL,
  `character` SMALLINT NULL,
  PRIMARY KEY (`users_id`, `debate_session_id`),
  INDEX `fk_users_has_debate_session_debate_session1_idx` (`debate_session_id` ASC) VISIBLE,
  INDEX `fk_users_has_debate_session_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_debate_session_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `dtc`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_debate_session_debate_session1`
    FOREIGN KEY (`debate_session_id`)
    REFERENCES `dtc`.`debate_session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
