-- MySQL Script generated by MySQL Workbench
-- Mon Nov  5 08:55:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`debate_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`debate_session` (
  `id` INT NOT NULL,
  `matchid` CHAR(36) NULL,
  `timestamp` TIMESTAMP NULL DEFAULT TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `pk_matchid` USING BTREE (`matchid`) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  `xp` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`debate_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`debate_review` (
  `id` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT TIMESTAMP(),
  `review` TEXT NOT NULL,
  `aggrement` TINYINT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_debate_review_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_debate_review_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`debate_session_reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`debate_session_reviews` (
  `debate_session_id` INT NOT NULL,
  `debate_review_id` INT NOT NULL,
  PRIMARY KEY (`debate_session_id`, `debate_review_id`),
  INDEX `fk_debate_session_has_debate_review_debate_review1_idx` (`debate_review_id` ASC) VISIBLE,
  INDEX `fk_debate_session_has_debate_review_debate_session_idx` (`debate_session_id` ASC) VISIBLE,
  CONSTRAINT `fk_debate_session_has_debate_review_debate_session`
    FOREIGN KEY (`debate_session_id`)
    REFERENCES `mydb`.`debate_session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_debate_session_has_debate_review_debate_review1`
    FOREIGN KEY (`debate_review_id`)
    REFERENCES `mydb`.`debate_review` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`debate_session_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`debate_session_users` (
  `users_id` INT NOT NULL,
  `debate_session_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `debate_session_id`),
  INDEX `fk_users_has_debate_session_debate_session1_idx` (`debate_session_id` ASC) VISIBLE,
  INDEX `fk_users_has_debate_session_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_debate_session_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_debate_session_debate_session1`
    FOREIGN KEY (`debate_session_id`)
    REFERENCES `mydb`.`debate_session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
