// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'disabled',
    'aws_cognito_identity_pool_id': 'us-east-1:5173fb21-e414-43bc-af6c-3a65de8caf22',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'disabled',
    'aws_content_delivery_bucket': 'dtc-hosting-mobilehub-871967846',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd6me3kyf47oy4.cloudfront.net',
    'aws_mobile_analytics_app_id': 'd603a092330a4667b13952dd97e6c780',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '842a85ef-0cf3-4602-beac-784388fbbf64',
    'aws_project_name': 'dtc',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'dtc-mobilehub-871967846',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_qnnbmLfh0',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '1a66tr0jclinub7j3ls0j3mutt',
}

export default awsmobile;
